"""create_initial_schema

Revision ID: b3d1e31edd8f
Revises: 
Create Date: 2026-09-11 19:29:03.847718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d1e31edd8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label_en', sa.String(length=100), nullable=False),
    sa.Column('label_hi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_categories_code'), 'education_categories', ['code'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_code'), 'sectors', ['code'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.Column('sector_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=True)
    op.create_table('internships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('stipend_inr', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allows_no_skills', sa.Boolean(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_deadline'), 'internships', ['deadline'], unique=False)
    op.create_index(op.f('ix_internships_district'), 'internships', ['district'], unique=False)
    op.create_index(op.f('ix_internships_id'), 'internships', ['id'], unique=False)
    op.create_index(op.f('ix_internships_is_active'), 'internships', ['is_active'], unique=False)
    op.create_index(op.f('ix_internships_sector_id'), 'internships', ['sector_id'], unique=False)
    op.create_index(op.f('ix_internships_state'), 'internships', ['state'], unique=False)
    op.create_index(op.f('ix_internships_title'), 'internships', ['title'], unique=False)
    op.create_table('internship_educations',
    sa.Column('internship_id', sa.String(length=32), nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['education_id'], ['education_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internship_id', 'education_id')
    )
    op.create_table('internship_skills',
    sa.Column('internship_id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internship_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internship_skills')
    op.drop_table('internship_educations')
    op.drop_index(op.f('ix_internships_title'), table_name='internships')
    op.drop_index(op.f('ix_internships_state'), table_name='internships')
    op.drop_index(op.f('ix_internships_sector_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_active'), table_name='internships')
    op.drop_index(op.f('ix_internships_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_district'), table_name='internships')
    op.drop_index(op.f('ix_internships_deadline'), table_name='internships')
    op.drop_table('internships')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_sectors_code'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_education_categories_code'), table_name='education_categories')
    op.drop_table('education_categories')
    # ### end Alembic commands ###
